### ISSUE TITLE
审核反馈

### ISSUE THREAD

**Issue by yi-Xu-0100** [inu1255/opendonate#1]
昨天看了下这个捐助，发现可以使用，所以捐助了5元表达感谢。

然后根据网站名字找到了这个开源项目，不知道能不能提供稍微细致的配置手册？

还有就是关于审核的问题，就是用户提交捐助后，这个待审核没有更新，这里是怎么解决这个付款确认信息的？还是说，得自己后台添加？

我查了下相关的捐助项目，没找到类似的方便的开源方案，希望能够提供配置和使用手册~

**Comment by yi-Xu-0100** [comment]
我查了下关于个人收款方式，貌似不太好走，有的都直接建议申请商户，不知道本项目实现方案是什么？需要什么资格申请吗？有没有相关的 api 方便调用？

**Comment by inu1255** [comment]
@yi-Xu-0100 
目前审核是需要自己后台手动处理的，这个项目应该还有很多bug,如果你打算本地跑一下试试，我更新了README
个人收款的话我了解的情况基本都是如下流程：
1. 上传个人收款二维码（微信/支付宝）定额/不定额都上传
2. 根据订单价格匹配收款码（优先用定额，没有的用不定额让用户自己输入）
3. 用户付款后手动或自动审核

关于自动审格的方案，我了解的是：
1. 通过安卓手机的辅助功能(AccessibilityService)监听消息通知，获取收款金额
2. 通过金额和时间段匹配订单（因为同一时间段同一金额的订单可能有多个，通常会把订单金额浮动几分钱用来区分）
但是听说个人收款会被风控，不适合大量收款（遗憾的是我从来没被风控过😂）

**Comment by yi-Xu-0100** [comment]
感谢回复，和我了解的情况类似，自动审核真的是太难了，不太想加这个辅助功能监听。

不过估计和我关系也不大就是……完全没有可用的开源项目等捐助😂。
